### ISSUE TITLE
images

### ISSUE THREAD

**Issue by larsbrubaker** [MatterHackers/MatterControl-Help#11]
![image](https://user-images.githubusercontent.com/1158332/42115063-62945b2e-7ba6-11e8-8f49-c2a2304377fe.png)

**Comment by jlewin** [comment]
What's this mean?

**Comment by larsbrubaker** [comment]
Sorry added this so I would have that image to reference in the repository's readme.md.

**Comment by jlewin** [comment]
Gotcha. I wasn't sure what was up given the disconnect between the title and the image and had to ask.

FYI: There's probably no need to save an issue for this use case. That act of pasting from the clipboard into the editor is enough to create and persist the image. If you paste into the editor, copy the injected Markdown image tag and paste it into some external content, you'll have working image that never seems to be destroyed

**Comment by jlewin** [comment]
Having said that, we should probably revise our workflow to avoid hosting image content from GitHub (as you're already doing by moving to MatterHackers.com). Hopefully we'll come up with something pain free going forward
